# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Build Server
      run: |
        cd server
        npm install
        npm run build

    - name: Build Client
      run: |
        cd client
        npm install
        npm run build

    - name: Package built code
      run: |
        mkdir release
        cp -r client/dist release/client
        cp -r server/dist release/server
        cd release
        tar -czf release.tar.gz client server

    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release/release.tar.gz
